#if !defined(AFX_CONTOURSERIES_H__1A9EA435_EEC4_4575_918E_9AC24E631BEB__INCLUDED_)
#define AFX_CONTOURSERIES_H__1A9EA435_EEC4_4575_918E_9AC24E631BEB__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CValueList;

/////////////////////////////////////////////////////////////////////////////
// CContourSeries wrapper class

class CContourSeries : public COleDispatchDriver
{
public:
	CContourSeries() {}		// Calls COleDispatchDriver default constructor
	CContourSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CContourSeries(const CContourSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long AddXYZ(long AX, double AY, long AZ, LPCTSTR AXLabel, unsigned long Value);
	void MaxZValue();
	void MinZValue();
	long GetTimesZOrder();
	void SetTimesZOrder(long nNewValue);
	CValueList GetZValues();
	double GetZValue(long Index);
	void SetZValue(long Index, double newValue);
	unsigned long GetEndColor();
	void SetEndColor(unsigned long newValue);
	long GetNumXValues();
	void SetNumXValues(long nNewValue);
	long GetNumZValues();
	void SetNumZValues(long nNewValue);
	long GetPaletteSteps();
	void SetPaletteSteps(long nNewValue);
	unsigned long GetStartColor();
	void SetStartColor(unsigned long newValue);
	BOOL GetUseColorRange();
	void SetUseColorRange(BOOL bNewValue);
	BOOL GetUsePalette();
	void SetUsePalette(BOOL bNewValue);
	double GetXZValue(long X, long Z);
	unsigned long GetSurfacePaletteColor(double Y);
	long AddPalette(double Value, unsigned long Color);
	void ClearPalette();
	void CreateDefaultPalette(long NumSteps);
	long GetNumLevels();
	void SetNumLevels(long nNewValue);
	BOOL GetYPositionLevel();
	void SetYPositionLevel(BOOL bNewValue);
	double GetYPosition();
	void SetYPosition(double newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CONTOURSERIES_H__1A9EA435_EEC4_4575_918E_9AC24E631BEB__INCLUDED_)
