#if !defined(AFX_CUSTOMSERIES_H__0C6B0E5C_7E01_422F_8B8A_837D3F88BA8E__INCLUDED_)
#define AFX_CUSTOMSERIES_H__0C6B0E5C_7E01_422F_8B8A_837D3F88BA8E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPointer;
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CCustomSeries wrapper class

class CCustomSeries : public COleDispatchDriver
{
public:
	CCustomSeries() {}		// Calls COleDispatchDriver default constructor
	CCustomSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCustomSeries(const CCustomSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CPointer GetPointer();
	BOOL GetStairs();
	void SetStairs(BOOL bNewValue);
	BOOL GetInvertedStairs();
	void SetInvertedStairs(BOOL bNewValue);
	CPen1 GetLinePen();
	long GetLineBrush();
	void SetLineBrush(long nNewValue);
	BOOL GetClickableLine();
	void SetClickableLine(BOOL bNewValue);
	long GetLineHeight();
	void SetLineHeight(long nNewValue);
	BOOL GetDark3D();
	void SetDark3D(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CUSTOMSERIES_H__0C6B0E5C_7E01_422F_8B8A_837D3F88BA8E__INCLUDED_)
