#if !defined(AFX_EXPORT_H__7071197F_FC31_4D87_A710_9D3A3FEFB231__INCLUDED_)
#define AFX_EXPORT_H__7071197F_FC31_4D87_A710_9D3A3FEFB231__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CExport wrapper class

class CExport : public COleDispatchDriver
{
public:
	CExport() {}		// Calls COleDispatchDriver default constructor
	CExport(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CExport(const CExport& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void CopyToClipboardBitmap();
	void CopyToClipboardMetafile(BOOL Enhanced);
	void SaveToBitmapFile(LPCTSTR Filename);
	void SaveToFile(LPCTSTR Filename);
	void SaveToJPEGFile(LPCTSTR Filename, BOOL Gray, long Performance, long Quality, long Width, long Height);
	void SaveToMetafile(LPCTSTR Filename);
	void SaveToMetafileEnh(LPCTSTR Filename);
	void ShowExport();
	CString SaveChartDialog();
	void ConvertTeeFileToText(LPCTSTR InputFile, LPCTSTR OutputFile);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_EXPORT_H__7071197F_FC31_4D87_A710_9D3A3FEFB231__INCLUDED_)
