#if !defined(AFX_POINT3DSERIES_H__DDFB49C7_E81B_4D7A_A28F_5D5B2D5A529E__INCLUDED_)
#define AFX_POINT3DSERIES_H__DDFB49C7_E81B_4D7A_A28F_5D5B2D5A529E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CValueList;
class CPointer;
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CPoint3DSeries wrapper class

class CPoint3DSeries : public COleDispatchDriver
{
public:
	CPoint3DSeries() {}		// Calls COleDispatchDriver default constructor
	CPoint3DSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPoint3DSeries(const CPoint3DSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long AddXYZ(long AX, double AY, long AZ, LPCTSTR AXLabel, unsigned long Value);
	void MaxZValue();
	void MinZValue();
	long GetTimesZOrder();
	void SetTimesZOrder(long nNewValue);
	CValueList GetZValues();
	double GetZValue(long Index);
	void SetZValue(long Index, double newValue);
	double GetDepthSize();
	void SetDepthSize(double newValue);
	CPointer GetPointer();
	CPen1 GetLinePen();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_POINT3DSERIES_H__DDFB49C7_E81B_4D7A_A28F_5D5B2D5A529E__INCLUDED_)
